//! shared vocabulary: webhook config/endpoint DTOs, Severity, AlertEnvelope, silence/ack/route rule shapes, persistence keys.
//! Mechanical move from core/alerting.rs.

use super::*;

pub(crate) const CONFIG_KEY: &str = "alerting_webhook_config";

pub(crate) const RETRY_CONFIG_KEY: &str = "alerting_retry_config";

pub(crate) const POLL_RETRY_SECS: u64 = 30;

pub(crate) const MAX_FETCH_PER_SCAN: usize = 50;

/// One toggle for each of the four alert sources.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct WebhookSources {
    pub metrics_exceeded: bool,
    pub sla_violated: bool,
    pub kill_switch_engaged: bool,
    pub plugin_crashed: bool,
}

impl Default for WebhookSources {
    fn default() -> Self {
        // all false — the user ticks each one after enabling the webhook
        Self {
            metrics_exceeded: false,
            sla_violated: false,
            kill_switch_engaged: false,
            plugin_crashed: false,
        }
    }
}

/// Webhook config. When `enabled = false` all fields are advisory and no request is sent.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct WebhookConfig {
    pub enabled: bool,
    pub url: String,
    pub min_interval_secs: u32,
    pub sources: WebhookSources,
    /// Custom headers (commonly used to carry the auth header for Slack / Discord).
    pub custom_headers: Vec<(String, String)>,
    /// Phase 52: `0` = Phase 47/49 legacy payload `{source, timestamp, data}` (default);
    /// `1` = canonical envelope `{schema_version, event_id, source, severity, tags, timestamp, payload}`。
    #[serde(default)]
    pub schema_version: u32,
}

/// Phase 49 — WebhookEndpoint DTO used by the frontend.
/// Almost identical in shape to `AlertingEndpointRow`, but `id` is generated by the frontend (uuid-ish) via the `add` command, and `created_at` is filled by the backend.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct WebhookEndpoint {
    /// Empty string = create (backend generates); non-empty = update.
    #[serde(default)]
    pub id: String,
    pub name: String,
    pub url: String,
    pub enabled: bool,
    pub headers: Vec<(String, String)>,
    #[serde(default)]
    pub secret: String,
    #[serde(default)]
    pub source_filter: Vec<String>,
    /// Phase 52: same as `WebhookConfig.schema_version` above. Defaults to 0 (backward compatible).
    #[serde(default)]
    pub schema_version: u32,
    /// Phase 57: per-endpoint template (`None` = use the default envelope; `Some(...)` = render this template,
    /// supporting `{{source}}` / `{{severity}}` / `{{timestamp}}` / `{{payload.x}}` + `{{#if expr}}`
    /// + `{{#each path}}`). See `render_template` for details.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub template: Option<String>,
    /// Phase 58: sample JSON entered by the user while editing the template in the settings UI, used as live preview input.
    /// `None` = use `{}` as envelope.payload when previewing. 16 KB cap, validated by the frontend before save.
    #[serde(
        default,
        rename = "templateSample",
        skip_serializing_if = "Option::is_none"
    )]
    pub template_sample: Option<String>,
    /// Phase 72 — per-source severity override. Overwrites envelope_severity during fanout.
    /// `Vec<(source, severity)>` exact match (not glob). Precedence: endpoint override > user hint > manifest > default.
    #[serde(default)]
    pub severity_overrides: Vec<(String, Severity)>,
}

/// Phase 52 — Severity level (coarse-grained, used for the canonical envelope + Slack color mapping).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum Severity {
    Info,
    Warn,
    Error,
    Critical,
}

impl Severity {
    pub fn as_str(self) -> &'static str {
        match self {
            Severity::Info => "info",
            Severity::Warn => "warn",
            Severity::Error => "error",
            Severity::Critical => "critical",
        }
    }
    pub fn parse(s: &str) -> Option<Severity> {
        match s.to_ascii_lowercase().as_str() {
            "info" => Some(Severity::Info),
            "warn" | "warning" => Some(Severity::Warn),
            "error" | "err" => Some(Severity::Error),
            "critical" | "crit" | "fatal" => Some(Severity::Critical),
            _ => None,
        }
    }
}

/// Phase 52 — Canonical envelope (JSON), v1 fields fixed + forward compatible.
/// Older webhook receivers can distinguish v0/v1 via the `schema_version` field.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct AlertEnvelope {
    pub schema_version: u32,
    pub event_id: String,
    pub source: String,
    pub severity: Severity,
    #[serde(default)]
    pub tags: Vec<String>,
    pub timestamp: u64, // unix seconds
    pub payload: serde_json::Value,
}

/// Phase 52 — Current schema version constant.
pub const ALERT_SCHEMA_VERSION: u32 = 1;

/// Phase 50 — SilenceRule DTO used by the frontend.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SilenceRule {
    /// Empty string = create (backend generates).
    #[serde(default)]
    pub id: String,
    pub name: String,
    /// `*` matches all / `plugin.metrics.*` prefix match / `exact.kind` exact match.
    #[serde(default = "default_kind_pattern")]
    pub kind_pattern: String,
    pub starts_at: u64,
    pub ends_at: u64,
    /// 7-bit bitmask (Mon=1, Tue=2, ..., Sun=64); 0 = never fires (rejected by validation).
    #[serde(default = "default_weekdays")]
    pub weekdays: u8,
    #[serde(default)]
    pub start_hour: u8,
    #[serde(default = "default_end_hour")]
    pub end_hour: u8,
}

fn default_kind_pattern() -> String {
    "*".into()
}

fn default_weekdays() -> u8 {
    127
}

fn default_end_hour() -> u8 {
    24
}

/// Phase 50 — AckRule DTO used by the frontend.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct AckRule {
    pub kind_pattern: String,
    /// Suppression window length (seconds); the frontend passes minutes and the backend converts.
    pub window_secs: u64,
}

/// Phase 51 — DSL RouteRule DTO used by the frontend (`when` + `then`).
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct RouteRule {
    #[serde(default)]
    pub id: String,
    pub name: String,
    #[serde(default = "default_route_priority")]
    pub priority: i32,
    #[serde(default = "default_route_enabled")]
    pub enabled: bool,
    #[serde(default = "default_kind_pattern")]
    pub kind_pattern: String,
    #[serde(default)]
    pub payload_path: Option<String>,
    #[serde(default)]
    pub payload_match: Option<String>,
    /// Phase 51 — legacy field, references a WebhookEndpoint id.
    /// Since Phase 66 prefer `recipients` (supports webhook / log:stderr / log:file / email:smtp).
    /// Kept for backward compatibility: when recipients is empty, fall back to `["webhook:{id}" for id in target_endpoint_ids]`.
    #[serde(default)]
    pub target_endpoint_ids: Vec<String>,
    /// Phase 66 — multi-channel recipient refs (each spec resolved by `notification::resolve_recipient`).
    #[serde(default)]
    pub recipients: Vec<String>,
    #[serde(default)]
    pub tags: Vec<String>,
    /// Phase 68 — temporal correlation condition: only when an event matching `pattern` occurred within the past `window_secs`
    /// does this route fan out. `None` means unconditional fanout.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub seen_in_last: Option<SeenInLastSpec>,
}

/// Phase 68 — Route temporal correlation condition.
/// `pattern` uses Phase 51's `kind_matches` glob (`*` / `**.*`).
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SeenInLastSpec {
    pub pattern: String,
    pub window_secs: u64,
}

fn default_route_priority() -> i32 {
    100
}

fn default_route_enabled() -> bool {
    true
}

/// Phase 51 — YAML import/export top-level format:
/// ```yaml
/// version: 1
/// rules:
///   - name: critical → ops
///     priority: 10
///     when:
///       kind_pattern: "plugin.metrics.*"
///       payload_path: "cpu_percent"
///       payload_match: ">=90"
///     then:
///       target_endpoint_ids: ["ep-oncall"]
///       tags: ["p1", "page"]
/// ```
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct RouteRuleYamlDoc {
    #[serde(default = "default_yaml_version")]
    pub version: u32,
    pub rules: Vec<RouteRule>,
}

fn default_yaml_version() -> u32 {
    1
}

impl Default for WebhookConfig {
    fn default() -> Self {
        Self {
            enabled: false,
            url: String::new(),
            min_interval_secs: 5,
            sources: WebhookSources::default(),
            custom_headers: Vec::new(),
            schema_version: 0,
        }
    }
}
