// OpenCapX integration for OMP (oh-my-pi) — auto-generated by `opencapx connect omp`.
// Safe to delete: removing this file uninstalls the integration.
//
// Two jobs:
// 1. Session lifecycle → `opencapx hook --agent omp --event <state>` (bubble / tray state).
// 2. Command rules → on every `tool_call`, ask the hook for a rewrite (PreToolUse payload on
//    stdin) and, on a hit, return `{ input }` — the replacement arguments the tool executes
//    with. OMP revalidates them against the tool schema and shows the revised command in its
//    approval prompt, so this must happen before the approval gate (it does).
//    A miss or an audit-only hit (danger shapes) returns nothing: the command runs as-is.
import { spawn, spawnSync } from "node:child_process"

const BIN = "__OPENCAPX_BIN__"
const AGENT = "omp"

export default function (pi: any) {
  const report = (state: string, ctx: any) => {
    try {
      const cwd = (ctx && ctx.cwd) || process.cwd()
      const file = ctx && ctx.sessionManager && ctx.sessionManager.getSessionFile ? ctx.sessionManager.getSessionFile() : null
      const p = spawn(BIN, ["hook", "--agent", AGENT, "--event", state, "--session", "omp:" + (file || cwd), "--project", cwd], { stdio: "ignore" })
      if (p && p.unref) p.unref()
    } catch (e) {}
  }
  pi.on("session_start", async (_e: any, ctx: any) => report("registered", ctx))
  pi.on("agent_start", async (_e: any, ctx: any) => report("working", ctx))
  pi.on("agent_end", async (_e: any, ctx: any) => report("done", ctx))
  pi.on("session_shutdown", async (_e: any, ctx: any) => report("done", ctx))

  pi.on("tool_call", async (event: any, ctx: any) => {
    try {
      if (!event || event.toolName !== "bash") return
      const input = event.input
      if (!input || typeof input.command !== "string" || !input.command) return
      const cwd = (ctx && ctx.cwd) || process.cwd()
      const p = spawnSync(BIN, ["hook", "--agent", AGENT], {
        input: JSON.stringify({
          hook_event_name: "PreToolUse",
          cwd: cwd,
          tool_name: "bash",
          tool_input: { command: input.command },
        }),
        cwd: cwd,
        encoding: "utf8",
      })
      if (!p || p.status !== 0) return
      const raw = String(p.stdout || "").trim()
      if (!raw) return
      let rewritten = ""
      try {
        const reply = JSON.parse(raw)
        rewritten = reply && reply.hookSpecificOutput && reply.hookSpecificOutput.updatedInput
          ? reply.hookSpecificOutput.updatedInput.command : ""
      } catch (e) { return }
      if (typeof rewritten !== "string" || !rewritten || rewritten === input.command) return
      return { input: { ...input, command: rewritten } }
    } catch (e) {}
  })
}
