import { t } from "../../i18n";
import { esc } from "../shared";
import { clearAllAggregations, onAddAggregation, refreshAlertingAggregations, updateAggTargetSeverityVisibility } from "./aggregations";
import { refreshAlerting, saveAlertingConfig, testAlertingWebhook } from "./config";
import { clearAllCorrelations, onAddCorrelation, refreshAlertingCorrelations } from "./correlations";
import { onDetectCycles, onRefreshTimeline } from "./cycles";
import { onAddEndpoint, onPreviewPredict, populateAlertingPreviewEndpointSelect, refreshAlertingEndpoints } from "./endpoints";
import { clearAllEscalations, onAddEscalation, refreshAlertingEscalations } from "./escalations";
import { onExportAlertingBundle, onImportAlertingBundle, onRotateBundleSecret } from "./presets";
import { onAddRecipient, refreshRecipients } from "./recipients";
import { clearAlertingResolved, refreshAlertingFailed, refreshAlertingRetryConfig, saveAlertingRetryConfig } from "./retry";
import { onAddRoute, onDryRunRoute, onExportRoutesYaml, onImportRoutesYaml, refreshAlertingRoutes } from "./routes";
import { clearAllSeverityHints, onAddSeverityHint, refreshAlertingSeverityHints } from "./severity";
import { onAckKind, onAddSilence, refreshAlertingAcks, refreshAlertingSilences } from "./silences";
import { onSimulateDispatch } from "./simulator";

export function renderAlerting(body: HTMLElement): void {
    // hero (enable dot + title + status slot) + section cards: the same depth language as the metrics/sla/plugin settings pages,
    // no settings-list wrapper (cards carry their own ring shadow; nesting looks dirty).
    body.innerHTML = `<div class="alerting-page">
      <header class="alerting-hero"><span class="alerting-dot" id="alerting-hero-dot" aria-hidden="true"></span><div class="alerting-hero-info"><span class="alerting-hero-title">${esc(t("tabAlerting"))}</span><span class="setting-hint" id="alerting-msg"></span></div></header>
      <div class="alerting-sect"><p class="alerting-sect-title">${esc(t("alertingHint"))}</p><div id="alerting-form"></div><div class="alerting-actions"><button class="btn" id="alerting-save" type="button">${esc(t("alertingSave"))}</button><button class="btn ghost" id="alerting-test" type="button">${esc(t("alertingTest"))}</button></div></div>
       <div class="alerting-sect"><p class="alerting-sect-title">${esc(t("alertingEndpointsHint"))}</p><div class="alerting-failed-head"><button class="btn" id="alerting-ep-add" type="button">${esc(t("alertingEndpointAdd"))}</button><button class="btn ghost" id="alerting-bundle-export" type="button" title="${esc(t("alertingBundleExportTitle"))}">${esc(t("alertingBundleExport"))}</button><button class="btn ghost" id="alerting-bundle-import" type="button" title="${esc(t("alertingBundleImportTitle"))}">${esc(t("alertingBundleImport"))}</button><button class="btn ghost" id="alerting-bundle-rotate" type="button" title="${esc(t("alertingBundleRotateTitle"))}">${esc(t("alertingBundleRotate"))}</button><span class="setting-hint" id="alerting-bundle-msg"></span></div><div id="alerting-endpoints-list"></div></div>
      <div class="alerting-sect alerting-preview-section"><p class="alerting-sect-title">${esc(t("alertingSeverityPreviewTitle"))}</p><span class="setting-hint">${esc(t("alertingSeverityPreviewHint"))}</span><div class="alerting-preview-controls"><input type="text" id="alerting-preview-source" class="logs-input" placeholder="${esc(t("alertingSeverityPreviewSource"))}" style="min-width:240px" /><select id="alerting-preview-endpoint" class="logs-input"><option value="">${esc(t("alertingSeverityPreviewAllEndpoints"))}</option></select><button id="alerting-preview-predict" class="btn" type="button">${esc(t("alertingSeverityPreviewButton"))}</button><span class="setting-hint" id="alerting-preview-msg"></span></div><div id="alerting-preview-result"></div></div>
       <div class="alerting-sect"><p class="alerting-sect-title">${esc(t("alertingDispatchSimulateTitle"))}</p><span class="setting-hint">${esc(t("alertingDispatchSimulateHint"))}</span><div class="alerting-simulation"><div class="alerting-sim-controls"><input type="text" id="alerting-sim-source" class="logs-input" placeholder="${esc(t("alertingDispatchSimulateSource"))}" style="min-width:240px" /><textarea id="alerting-sim-payload" class="logs-input alerting-sim-payload" rows="2" placeholder="${esc(t("alertingDispatchSimulatePayload"))}"></textarea><button id="alerting-sim-btn" class="btn" type="button">${esc(t("alertingDispatchSimulateButton"))}</button><span class="setting-hint" id="alerting-sim-msg"></span></div><div id="alerting-sim-result"></div></div></div>
       <div class="alerting-sect"><p class="alerting-sect-title">${esc(t("alertingRetryConfig"))}</p><div id="alerting-retry-form"></div><div class="alerting-actions"><button class="btn" id="alerting-retry-save" type="button">${esc(t("alertingSave"))}</button><span class="setting-hint" id="alerting-retry-msg"></span></div></div>
       <div class="alerting-sect"><p class="alerting-sect-title">${esc(t("alertingFailedTitle"))}</p><div class="alerting-failed-head"><select class="logs-input" id="alerting-failed-state"><option value="">${esc(t("alertingFailedStateAll"))}</option><option value="pending">${esc(t("alertingFailedStatePending"))}</option><option value="exhausted">${esc(t("alertingFailedStateExhausted"))}</option></select><button class="btn ghost" id="alerting-failed-refresh" type="button">${esc(t("alertingFailedRefresh"))}</button><button class="btn ghost" id="alerting-failed-clear" type="button">${esc(t("alertingClearExhausted"))}</button><span class="setting-hint" id="alerting-failed-msg"></span></div><div id="alerting-failed-list"></div></div>
       <div class="alerting-sect"><p class="alerting-sect-title">${esc(t("alertingSilencesHint"))}</p><div class="alerting-failed-head"><button class="btn" id="alerting-silence-add" type="button">${esc(t("alertingSilencesAdd"))}</button><span class="setting-hint" id="alerting-silence-msg"></span></div><div id="alerting-silences-list"></div></div>
       <div class="alerting-sect"><p class="alerting-sect-title">${esc(t("alertingAcksHint"))}</p><div class="alerting-failed-head"><input type="text" class="logs-input" id="alerting-ack-pattern" placeholder="${esc(t("alertingAckPattern"))}" style="min-width:240px"/><input type="number" class="logs-input" id="alerting-ack-window" min="1" max="604800" value="3600" style="width:90px"/><button class="btn" id="alerting-ack-btn" type="button">${esc(t("alertingAck"))}</button><span class="setting-hint" id="alerting-ack-msg"></span></div><div id="alerting-acks-list"></div></div>
       <div class="alerting-sect"><p class="alerting-sect-title">${esc(t("alertingRecipientsHint"))}</p><div class="alerting-failed-head"><button class="btn" id="alerting-recipient-add" type="button" title="${esc(t("alertingRecipientAddTitle"))}">${esc(t("alertingRecipientAdd"))}</button><span class="setting-hint" id="alerting-recipients-msg"></span></div><div id="alerting-recipients-list"></div></div>
       <div class="alerting-sect"><p class="alerting-sect-title">${esc(t("alertingRoutesHint"))}</p><div class="alerting-failed-head"><button class="btn" id="alerting-route-add" type="button">${esc(t("alertingRouteAdd"))}</button><button class="btn ghost" id="alerting-route-import" type="button">${esc(t("alertingRouteImport"))}</button><button class="btn ghost" id="alerting-route-export" type="button">${esc(t("alertingRouteExport"))}</button><button class="btn ghost" id="alerting-route-dryrun" type="button">${esc(t("alertingRouteDryRun"))}</button><span class="setting-hint" id="alerting-route-msg"></span></div><div id="alerting-routes-list"></div></div>
       <div class="alerting-sect"><p class="alerting-sect-title">${esc(t("alertingSeverityHintsHint"))}</p><div class="alerting-failed-head"><input type="text" class="logs-input" id="severity-hint-source" placeholder="${esc(t("alertingSeverityHintSource"))}" style="min-width:240px"/><select class="logs-input" id="severity-hint-severity"><option value="info">info</option><option value="warn">warn</option><option value="error">error</option><option value="critical">critical</option></select><button class="btn" id="severity-hint-add" type="button">${esc(t("alertingSeverityHintsAdd"))}</button><button class="btn ghost" id="severity-hints-clear" type="button">${esc(t("alertingSeverityHintsClear"))}</button><span class="setting-hint" id="severity-hints-msg"></span></div><div class="setting-hint setting-hint-propagation-banner">${esc(t("alertingSeverityPropagationBanner"))}</div><div id="alerting-severity-hints-list"></div><div id="alerting-severity-chain-result"></div><div id="alerting-severity-propagation-result"></div><div id="alerting-severity-cascade-result"></div></div>
       <div class="alerting-sect"><p class="alerting-sect-title">${esc(t("alertingAggregationsHint"))}</p><div class="alerting-failed-head"><input type="text" class="logs-input" id="agg-name" placeholder="${esc(t("alertingAggregationName"))}" style="min-width:160px"/><input type="text" class="logs-input" id="agg-pattern" placeholder="${esc(t("alertingAggregationPattern"))}" value="*" style="min-width:140px"/><input type="number" class="logs-input" id="agg-window" min="1" max="86400" value="60" style="width:72px" title="${esc(t("alertingAggregationWindow"))}"/><input type="number" class="logs-input" id="agg-threshold" min="1" max="10000" value="3" style="width:64px" title="${esc(t("alertingAggregationThreshold"))}"/><select class="logs-input" id="agg-action"><option value="suppress">suppress</option><option value="downgrade">downgrade</option><option value="merge">merge</option></select><select class="logs-input" id="agg-target-severity" title="${esc(t("alertingAggregationTargetSeverity"))}"><option value="info">info</option><option value="warn">warn</option><option value="error">error</option><option value="critical">critical</option></select><button class="btn" id="agg-add" type="button">${esc(t("alertingAggregationAdd"))}</button><button class="btn ghost" id="agg-clear" type="button">${esc(t("alertingAggregationClear"))}</button><span class="setting-hint" id="agg-msg"></span></div><div id="alerting-aggregations-list"></div></div>
       <div class="alerting-sect"><p class="alerting-sect-title">${esc(t("alertingCorrelationsHint"))}</p><div class="alerting-failed-head"><input type="text" class="logs-input" id="corr-name" placeholder="${esc(t("alertingCorrelationName"))}" style="min-width:160px"/><input type="text" class="logs-input" id="corr-pattern-a" placeholder="${esc(t("alertingCorrelationPatternA"))}" style="min-width:160px"/><span class="setting-hint">→</span><input type="text" class="logs-input" id="corr-pattern-b" placeholder="${esc(t("alertingCorrelationPatternB"))}" style="min-width:160px"/><input type="number" class="logs-input" id="corr-window" min="1" max="86400" value="30" style="width:72px" title="${esc(t("alertingCorrelationWindow"))}"/><button class="btn" id="corr-add" type="button">${esc(t("alertingCorrelationAdd"))}</button><button class="btn ghost" id="corr-clear" type="button">${esc(t("alertingCorrelationClear"))}</button><span class="setting-hint" id="corr-msg"></span></div><div id="alerting-correlations-list"></div></div>
       <div class="alerting-sect"><p class="alerting-sect-title">${esc(t("alertingEscalationsHint"))}</p><div class="alerting-failed-head"><input type="text" class="logs-input" id="esc-name" placeholder="${esc(t("alertingEscalationName"))}" style="min-width:160px"/><input type="text" class="logs-input" id="esc-pattern" placeholder="${esc(t("alertingEscalationPattern"))}" value="*" style="min-width:140px"/><input type="number" class="logs-input" id="esc-after" min="1" max="86400" value="60" style="width:72px" title="${esc(t("alertingEscalationAfter"))}"/><select class="logs-input" id="esc-target-severity" title="${esc(t("alertingEscalationTargetSeverity"))}"><option value="info">info</option><option value="warn">warn</option><option value="error">error</option><option value="critical">critical</option></select><input type="text" class="logs-input" id="esc-endpoints" placeholder="${esc(t("alertingEscalationEndpoints"))}" style="min-width:200px"/><button class="btn" id="esc-add" type="button">${esc(t("alertingEscalationAdd"))}</button><button class="btn ghost" id="esc-clear" type="button">${esc(t("alertingEscalationClear"))}</button><span class="setting-hint" id="esc-msg"></span></div><div id="alerting-escalations-list"></div></div>
       <div class="alerting-sect"><p class="alerting-sect-title">${esc(t("alertingCorrelationSectionTitle"))}</p><div class="alerting-failed-head"><button class="btn" id="alerting-correlation-cycles" type="button">${esc(t("alertingCorrelationDetectCycles"))}</button><button class="btn ghost" id="alerting-correlation-refresh" type="button">${esc(t("alertingCorrelationRecentEvents"))}</button><span class="setting-hint" id="alerting-correlation-msg"></span></div><div id="alerting-correlation-cycles-result"></div><div id="alerting-correlation-timeline"></div></div>
    </div>`;
    document.getElementById("alerting-save")?.addEventListener("click", () => void saveAlertingConfig());
    document.getElementById("alerting-test")?.addEventListener("click", () => void testAlertingWebhook());
    document.getElementById("alerting-ep-add")?.addEventListener("click", () => void onAddEndpoint());
    document.getElementById("alerting-bundle-export")?.addEventListener("click", () => void onExportAlertingBundle());
    document.getElementById("alerting-bundle-import")?.addEventListener("click", () => void onImportAlertingBundle());
    document.getElementById("alerting-bundle-rotate")?.addEventListener("click", () => void onRotateBundleSecret());
    // Phase 74: predict button — populate the endpoint select, then invoke
    populateAlertingPreviewEndpointSelect();
    document.getElementById("alerting-preview-predict")?.addEventListener("click", () => void onPreviewPredict());
    // Phase 75: full-chain dry-run simulate button
    document.getElementById("alerting-sim-btn")?.addEventListener("click", () => void onSimulateDispatch());
    document.getElementById("alerting-retry-save")?.addEventListener("click", () => void saveAlertingRetryConfig());
    document.getElementById("alerting-failed-refresh")?.addEventListener("click", () => void refreshAlertingFailed());
    document.getElementById("alerting-failed-clear")?.addEventListener("click", () => void clearAlertingResolved());
    document.getElementById("alerting-failed-state")?.addEventListener("change", () => void refreshAlertingFailed());
    document.getElementById("alerting-silence-add")?.addEventListener("click", () => void onAddSilence());
    document.getElementById("alerting-ack-btn")?.addEventListener("click", () => void onAckKind());
    document.getElementById("alerting-route-add")?.addEventListener("click", () => void onAddRoute());
    document.getElementById("alerting-route-import")?.addEventListener("click", () => void onImportRoutesYaml());
    document.getElementById("alerting-route-export")?.addEventListener("click", () => void onExportRoutesYaml());
    document.getElementById("alerting-route-dryrun")?.addEventListener("click", () => void onDryRunRoute());
    document.getElementById("alerting-recipient-add")?.addEventListener("click", () => void onAddRecipient());
    void refreshRecipients();
    document.getElementById("severity-hint-add")?.addEventListener("click", () => void onAddSeverityHint());
    document.getElementById("severity-hints-clear")?.addEventListener("click", () => void clearAllSeverityHints());
    document.getElementById("agg-add")?.addEventListener("click", () => void onAddAggregation());
    document.getElementById("agg-clear")?.addEventListener("click", () => void clearAllAggregations());
    document.getElementById("agg-action")?.addEventListener("change", () => void updateAggTargetSeverityVisibility());
    document.getElementById("corr-add")?.addEventListener("click", () => void onAddCorrelation());
    document.getElementById("corr-clear")?.addEventListener("click", () => void clearAllCorrelations());
    document.getElementById("esc-add")?.addEventListener("click", () => void onAddEscalation());
    document.getElementById("esc-clear")?.addEventListener("click", () => void clearAllEscalations());
    document.getElementById("alerting-correlation-cycles")?.addEventListener("click", () => void onDetectCycles());
    document.getElementById("alerting-correlation-refresh")?.addEventListener("click", () => void onRefreshTimeline());
    void refreshAlerting();
    void refreshAlertingRetryConfig();
    void refreshAlertingFailed();
    void refreshAlertingEndpoints();
    void refreshAlertingSilences();
    void refreshAlertingAcks();
    void refreshAlertingRoutes();
    void refreshAlertingSeverityHints();
    void refreshAlertingAggregations();
    void refreshAlertingCorrelations();
    void refreshAlertingEscalations();
}
