//! the alerting-domain accessors (failed deliveries, endpoints, presets, silences, acks, routes, recipients, severity hints, aggregations, correlations, escalations).
//! Mechanical move from core/storage.rs.

use super::*;

impl Storage {
    /// Write a dead-letter record (state='pending'). `id` is generated by the caller (nano timestamp or uuid).
    /// Phase 49 adds `endpoint_id`: None means it came from the Phase 47 single-endpoint compatibility path.
    pub fn insert_failed_delivery(
        &mut self,
        id: &str,
        source: &str,
        url: &str,
        payload_json: &str,
        now_ts: u64,
        max_attempts: u32,
        next_retry_ts: u64,
        last_error: &str,
        endpoint_id: Option<&str>,
    ) {
        let _ = self.conn.execute(
            "INSERT INTO alerting_failed_deliveries
                (id, source, url, payload, first_attempt_ts, last_attempt_ts,
                 attempts, max_attempts, last_error, next_retry_ts, state, endpoint_id)
             VALUES (?1, ?2, ?3, ?4, ?5, ?5, 1, ?6, ?7, ?8, 'pending', ?9)",
            rusqlite::params![
                id,
                source,
                url,
                payload_json,
                now_ts as i64,
                max_attempts as i64,
                last_error,
                next_retry_ts as i64,
                endpoint_id,
            ],
        );
    }

    /// List dead letters for a given state (state nullable: "pending"/"exhausted"/"resolved"). By next_retry_ts ascending.
    pub fn list_failed_deliveries(
        &self,
        state: Option<&str>,
        limit: usize,
    ) -> Vec<FailedDeliveryRow> {
        let limit = limit.max(1).min(2000);
        let (sql, use_state): (&str, bool) = match state {
            Some(s) if !s.is_empty() => (
                "SELECT id, source, url, payload, first_attempt_ts, last_attempt_ts,
                        attempts, max_attempts, last_error, next_retry_ts, state, endpoint_id
                   FROM alerting_failed_deliveries
                   WHERE state = ?1
                   ORDER BY next_retry_ts ASC, last_attempt_ts DESC
                   LIMIT ?2",
                true,
            ),
            _ => (
                "SELECT id, source, url, payload, first_attempt_ts, last_attempt_ts,
                        attempts, max_attempts, last_error, next_retry_ts, state, endpoint_id
                   FROM alerting_failed_deliveries
                   ORDER BY next_retry_ts ASC, last_attempt_ts DESC
                   LIMIT ?1",
                false,
            ),
        };
        let Ok(mut stmt) = self.conn.prepare(sql) else {
            return Vec::new();
        };
        let mapper = |r: &rusqlite::Row| -> rusqlite::Result<FailedDeliveryRow> {
            let payload: String = r.get(3)?;
            Ok(FailedDeliveryRow {
                id: r.get(0)?,
                source: r.get(1)?,
                url: r.get(2)?,
                payload,
                first_attempt_ts: r.get::<_, i64>(4)? as u64,
                last_attempt_ts: r.get::<_, i64>(5)? as u64,
                attempts: r.get::<_, i64>(6)? as u32,
                max_attempts: r.get::<_, i64>(7)? as u32,
                last_error: r.get(8)?,
                next_retry_ts: r.get::<_, i64>(9)? as u64,
                state: r.get(10)?,
                endpoint_id: r.get(11)?,
            })
        };
        if use_state {
            stmt.query_map(rusqlite::params![state.unwrap(), limit as i64], mapper)
                .ok()
                .map(|i| i.filter_map(|x| x.ok()).collect())
                .unwrap_or_default()
        } else {
            stmt.query_map(rusqlite::params![limit as i64], mapper)
                .ok()
                .map(|i| i.filter_map(|x| x.ok()).collect())
                .unwrap_or_default()
        }
    }

    /// Fetch due pending rows (called by the retry loop). limit defaults to 50 to avoid scanning too many at once.
    pub fn fetch_due_failed_deliveries(&self, now_ts: u64, limit: usize) -> Vec<FailedDeliveryRow> {
        let Ok(mut stmt) = self.conn.prepare(
            "SELECT id, source, url, payload, first_attempt_ts, last_attempt_ts,
                    attempts, max_attempts, last_error, next_retry_ts, state, endpoint_id
               FROM alerting_failed_deliveries
               WHERE state = 'pending' AND next_retry_ts <= ?1
               ORDER BY next_retry_ts ASC
               LIMIT ?2",
        ) else {
            return Vec::new();
        };
        stmt.query_map(rusqlite::params![now_ts as i64, limit as i64], |r| {
            let payload: String = r.get(3)?;
            Ok(FailedDeliveryRow {
                id: r.get(0)?,
                source: r.get(1)?,
                url: r.get(2)?,
                payload,
                first_attempt_ts: r.get::<_, i64>(4)? as u64,
                last_attempt_ts: r.get::<_, i64>(5)? as u64,
                attempts: r.get::<_, i64>(6)? as u32,
                max_attempts: r.get::<_, i64>(7)? as u32,
                last_error: r.get(8)?,
                next_retry_ts: r.get::<_, i64>(9)? as u64,
                state: r.get(10)?,
                endpoint_id: r.get(11)?,
            })
        })
        .ok()
        .map(|i| i.filter_map(|x| x.ok()).collect())
        .unwrap_or_default()
    }

    /// Phase 49: delete all dead letters for the given endpoint (cascade cleanup).
    pub fn delete_failed_deliveries_for_endpoint(&mut self, endpoint_id: &str) -> usize {
        self.conn
            .execute(
                "DELETE FROM alerting_failed_deliveries WHERE endpoint_id = ?1",
                rusqlite::params![endpoint_id],
            )
            .unwrap_or(0)
    }

    /// Update a failed retry: attempts++, refreshing last_attempt_ts / last_error / next_retry_ts.
    /// Passing next_retry_ts = 0 means "exhausted"; state switches to 'exhausted'.
    pub fn update_failed_delivery_retry(
        &mut self,
        id: &str,
        now_ts: u64,
        next_retry_ts: u64,
        last_error: &str,
    ) {
        let _ = self.conn.execute(
            "UPDATE alerting_failed_deliveries
                SET attempts = attempts + 1,
                    last_attempt_ts = ?2,
                    last_error = ?3,
                    next_retry_ts = ?4,
                    state = CASE WHEN ?4 = 0 THEN 'exhausted' ELSE 'pending' END
              WHERE id = ?1",
            rusqlite::params![id, now_ts as i64, last_error, next_retry_ts as i64],
        );
    }

    /// Mark as resolved (2xx response). state='resolved', kept for N days before cleanup.
    pub fn mark_failed_delivery_resolved(&mut self, id: &str, now_ts: u64) {
        let _ = self.conn.execute(
            "UPDATE alerting_failed_deliveries
                SET state = 'resolved', last_attempt_ts = ?2
              WHERE id = ?1",
            rusqlite::params![id, now_ts as i64],
        );
    }

    /// Manual retry: reset attempts to zero, state back to 'pending', next_retry_ts=now.
    pub fn reset_failed_delivery_for_retry(&mut self, id: &str, now_ts: u64) {
        let _ = self.conn.execute(
            "UPDATE alerting_failed_deliveries
                SET state = 'pending', attempts = 0, next_retry_ts = ?2, last_error = 'manual retry'
              WHERE id = ?1",
            rusqlite::params![id, now_ts as i64],
        );
    }

    /// Delete a dead letter.
    pub fn delete_failed_delivery(&mut self, id: &str) -> bool {
        let n = self
            .conn
            .execute(
                "DELETE FROM alerting_failed_deliveries WHERE id = ?1",
                rusqlite::params![id],
            )
            .unwrap_or(0);
        n > 0
    }

    /// Clear all exhausted + resolved rows (user manually empties the panel).
    pub fn clear_resolved_failed_deliveries(&mut self) -> usize {
        self.conn
            .execute(
                "DELETE FROM alerting_failed_deliveries WHERE state IN ('exhausted','resolved')",
                [],
            )
            .unwrap_or(0)
    }

    /// Prune resolved / exhausted rows older than retention_days (to avoid long-term buildup).
    pub fn prune_old_failed_deliveries(&mut self, now_ts: u64, retention_days: u32) {
        let cutoff = now_ts.saturating_sub((retention_days as u64).saturating_mul(86400));
        let _ = self.conn.execute(
            "DELETE FROM alerting_failed_deliveries
              WHERE state IN ('exhausted','resolved') AND last_attempt_ts < ?1",
            rusqlite::params![cutoff as i64],
        );
    }

    fn parse_endpoint_row(
        &self,
        id: String,
        name: String,
        url: String,
        enabled: i64,
        headers_json: String,
        secret: String,
        source_filter_json: String,
        created_at: i64,
        schema_version: i64,
        template: Option<String>,
        template_sample: Option<String>,
        severity_overrides: Option<String>,
    ) -> AlertingEndpointRow {
        let headers: Vec<(String, String)> =
            serde_json::from_str(&headers_json).unwrap_or_default();
        let source_filter: Vec<String> =
            serde_json::from_str(&source_filter_json).unwrap_or_default();
        AlertingEndpointRow {
            id,
            name,
            url,
            enabled: enabled != 0,
            headers,
            secret,
            source_filter,
            created_at: created_at as u64,
            schema_version: schema_version.max(0) as u32,
            template,
            template_sample,
            severity_overrides,
        }
    }

    /// List all endpoints, by created_at ascending.
    pub fn list_alerting_endpoints(&self) -> Vec<AlertingEndpointRow> {
        let Ok(mut stmt) = self.conn.prepare(
            "SELECT id, name, url, enabled, headers_json, secret, source_filter_json, created_at, schema_version, template, template_sample, severity_overrides_json
               FROM alerting_endpoints ORDER BY created_at ASC",
        ) else {
            return Vec::new();
        };
        stmt.query_map([], |r| {
            Ok((
                r.get::<_, String>(0)?,
                r.get::<_, String>(1)?,
                r.get::<_, String>(2)?,
                r.get::<_, i64>(3)?,
                r.get::<_, String>(4)?,
                r.get::<_, String>(5)?,
                r.get::<_, String>(6)?,
                r.get::<_, i64>(7)?,
                r.get::<_, i64>(8)?,
                r.get::<_, Option<String>>(9)?,
                r.get::<_, Option<String>>(10)?,
                r.get::<_, Option<String>>(11)?,
            ))
        })
        .ok()
        .map(|i| {
            i.filter_map(|x| x.ok())
                .map(
                    |(id, name, url, en, hj, sec, sfj, ca, sv, tpl, tpl_s, so)| {
                        self.parse_endpoint_row(
                            id, name, url, en, hj, sec, sfj, ca, sv, tpl, tpl_s, so,
                        )
                    },
                )
                .collect()
        })
        .unwrap_or_default()
    }

    /// List all enabled endpoints — used during dispatcher fanout.
    pub fn list_enabled_alerting_endpoints(&self) -> Vec<AlertingEndpointRow> {
        let Ok(mut stmt) = self.conn.prepare(
            "SELECT id, name, url, enabled, headers_json, secret, source_filter_json, created_at, schema_version, template, template_sample, severity_overrides_json
               FROM alerting_endpoints WHERE enabled = 1 ORDER BY created_at ASC",
        ) else {
            return Vec::new();
        };
        stmt.query_map([], |r| {
            Ok((
                r.get::<_, String>(0)?,
                r.get::<_, String>(1)?,
                r.get::<_, String>(2)?,
                r.get::<_, i64>(3)?,
                r.get::<_, String>(4)?,
                r.get::<_, String>(5)?,
                r.get::<_, String>(6)?,
                r.get::<_, i64>(7)?,
                r.get::<_, i64>(8)?,
                r.get::<_, Option<String>>(9)?,
                r.get::<_, Option<String>>(10)?,
                r.get::<_, Option<String>>(11)?,
            ))
        })
        .ok()
        .map(|i| {
            i.filter_map(|x| x.ok())
                .map(
                    |(id, name, url, en, hj, sec, sfj, ca, sv, tpl, tpl_s, so)| {
                        self.parse_endpoint_row(
                            id, name, url, en, hj, sec, sfj, ca, sv, tpl, tpl_s, so,
                        )
                    },
                )
                .collect()
        })
        .unwrap_or_default()
    }

    /// Get a single endpoint by id.
    pub fn get_alerting_endpoint(&self, id: &str) -> Option<AlertingEndpointRow> {
        let mut stmt = self
            .conn
            .prepare(
                "SELECT id, name, url, enabled, headers_json, secret, source_filter_json, created_at, schema_version, template, template_sample, severity_overrides_json
                   FROM alerting_endpoints WHERE id = ?1",
            )
            .ok()?;
        stmt.query_row(rusqlite::params![id], |r| {
            Ok((
                r.get::<_, String>(0)?,
                r.get::<_, String>(1)?,
                r.get::<_, String>(2)?,
                r.get::<_, i64>(3)?,
                r.get::<_, String>(4)?,
                r.get::<_, String>(5)?,
                r.get::<_, String>(6)?,
                r.get::<_, i64>(7)?,
                r.get::<_, i64>(8)?,
                r.get::<_, Option<String>>(9)?,
                r.get::<_, Option<String>>(10)?,
                r.get::<_, Option<String>>(11)?,
            ))
        })
        .ok()
        .map(
            |(id, name, url, en, hj, sec, sfj, ca, sv, tpl, tpl_s, so)| {
                self.parse_endpoint_row(id, name, url, en, hj, sec, sfj, ca, sv, tpl, tpl_s, so)
            },
        )
    }

    /// Upsert: update when there is an id, otherwise use the passed-in id (generated by the caller).
    pub fn upsert_alerting_endpoint(&mut self, row: &AlertingEndpointRow) {
        let headers_json = serde_json::to_string(&row.headers).unwrap_or_else(|_| "[]".into());
        let source_filter_json =
            serde_json::to_string(&row.source_filter).unwrap_or_else(|_| "[]".into());
        let _ = self.conn.execute(
            "INSERT INTO alerting_endpoints
                (id, name, url, enabled, headers_json, secret, source_filter_json, created_at, schema_version, template, template_sample, severity_overrides_json)
             VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10, ?11, ?12)
             ON CONFLICT(id) DO UPDATE SET
                name=excluded.name,
                url=excluded.url,
                enabled=excluded.enabled,
                headers_json=excluded.headers_json,
                secret=excluded.secret,
                source_filter_json=excluded.source_filter_json,
                schema_version=excluded.schema_version,
                template=excluded.template,
                template_sample=excluded.template_sample,
                severity_overrides_json=excluded.severity_overrides_json",
            rusqlite::params![
                row.id,
                row.name,
                row.url,
                if row.enabled { 1i64 } else { 0i64 },
                headers_json,
                row.secret,
                source_filter_json,
                row.created_at as i64,
                row.schema_version as i64,
                row.template.as_deref(),
                row.template_sample.as_deref(),
                row.severity_overrides.as_deref(),
            ],
        );
    }

    /// Delete an endpoint, cascading cleanup of its dead letters. Returns (endpoint_deleted, deliveries_deleted).
    pub fn delete_alerting_endpoint(&mut self, id: &str) -> (bool, usize) {
        let n = self
            .conn
            .execute(
                "DELETE FROM alerting_endpoints WHERE id = ?1",
                rusqlite::params![id],
            )
            .unwrap_or(0);
        let cleared = self.delete_failed_deliveries_for_endpoint(id);
        (n > 0, cleared)
    }

    /// List user-defined presets (builtins always live in the `core::alerting::BUILTIN_PRESETS` constant).
    pub fn list_user_template_presets(&self) -> Result<Vec<TemplatePresetRow>, String> {
        let mut stmt = self.conn.prepare(
            "SELECT id, name, description, kind, template, sample, builtin, version, changelog, created_at
               FROM template_presets WHERE builtin = 0 ORDER BY created_at ASC",
        ).map_err(|e| format!("prepare list_user_template_presets: {}", e))?;
        let rows = stmt
            .query_map([], |r| {
                Ok((
                    r.get::<_, String>(0)?,
                    r.get::<_, String>(1)?,
                    r.get::<_, Option<String>>(2)?,
                    r.get::<_, String>(3)?,
                    r.get::<_, String>(4)?,
                    r.get::<_, Option<String>>(5)?,
                    r.get::<_, i64>(6)?,
                    r.get::<_, i64>(7)?,
                    r.get::<_, Option<String>>(8)?,
                    r.get::<_, i64>(9)?,
                ))
            })
            .map_err(|e| format!("query list_user_template_presets: {}", e))?;
        let mut out = Vec::new();
        for row in rows {
            let (
                id,
                name,
                description,
                kind,
                template,
                sample,
                builtin,
                version,
                changelog,
                created_at,
            ) = row.map_err(|e| format!("row: {}", e))?;
            out.push(TemplatePresetRow {
                id,
                name,
                description,
                kind,
                template,
                sample,
                builtin: builtin != 0,
                version: version.max(1) as u32,
                changelog,
                created_at: created_at.max(0) as u64,
            });
        }
        Ok(out)
    }

    /// Upsert preset; `builtin=true` is also allowed (so builtin rows can still be persisted when exported/imported).
    /// Phase 60 — adds `version` + `changelog` columns; upsert writes both (allows resetting version = 1 on import).
    pub fn upsert_template_preset(&mut self, p: &TemplatePresetRow) -> Result<(), String> {
        let _ = self.conn.execute(
            "INSERT INTO template_presets
                (id, name, description, kind, template, sample, builtin, version, changelog, created_at)
             VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10)
             ON CONFLICT(id) DO UPDATE SET
                name=excluded.name,
                description=excluded.description,
                kind=excluded.kind,
                template=excluded.template,
                sample=excluded.sample,
                builtin=excluded.builtin,
                version=excluded.version,
                changelog=excluded.changelog",
            rusqlite::params![
                p.id,
                p.name,
                p.description.as_deref(),
                p.kind,
                p.template,
                p.sample.as_deref(),
                if p.builtin { 1i64 } else { 0i64 },
                p.version as i64,
                p.changelog.as_deref(),
                p.created_at as i64,
            ],
        ).map_err(|e| format!("upsert template_preset: {}", e))?;
        Ok(())
    }

    /// Delete only builtin=0 rows (avoid accidental deletion of built-ins). Returns true when actually deleted.
    pub fn delete_template_preset(&mut self, id: &str) -> bool {
        let n = self
            .conn
            .execute(
                "DELETE FROM template_presets WHERE id = ?1 AND builtin = 0",
                rusqlite::params![id],
            )
            .unwrap_or(0);
        n > 0
    }

    /// List all silence rules, by starts_at ascending.
    pub fn list_alerting_silences(&self) -> Vec<SilenceRuleRow> {
        let Ok(mut stmt) = self.conn.prepare(
            "SELECT id, name, kind_pattern, starts_at, ends_at, weekdays, start_hour, end_hour, created_at
               FROM alerting_silences ORDER BY starts_at ASC",
        ) else {
            return Vec::new();
        };
        stmt.query_map([], |r| {
            Ok(SilenceRuleRow {
                id: r.get(0)?,
                name: r.get(1)?,
                kind_pattern: r.get(2)?,
                starts_at: r.get::<_, i64>(3)? as u64,
                ends_at: r.get::<_, i64>(4)? as u64,
                weekdays: r.get::<_, i64>(5)? as u8,
                start_hour: r.get::<_, i64>(6)? as u8,
                end_hour: r.get::<_, i64>(7)? as u8,
                created_at: r.get::<_, i64>(8)? as u64,
            })
        })
        .ok()
        .map(|i| i.filter_map(|x| x.ok()).collect())
        .unwrap_or_default()
    }

    /// List all silences that could be active (ends_at > now + some buffer); the dispatch phase avoids querying all to prevent staleness.
    pub fn list_active_silences(&self, now_ts: u64) -> Vec<SilenceRuleRow> {
        let Ok(mut stmt) = self.conn.prepare(
            "SELECT id, name, kind_pattern, starts_at, ends_at, weekdays, start_hour, end_hour, created_at
               FROM alerting_silences WHERE ends_at > ?1 ORDER BY starts_at ASC",
        ) else {
            return Vec::new();
        };
        stmt.query_map(rusqlite::params![now_ts as i64], |r| {
            Ok(SilenceRuleRow {
                id: r.get(0)?,
                name: r.get(1)?,
                kind_pattern: r.get(2)?,
                starts_at: r.get::<_, i64>(3)? as u64,
                ends_at: r.get::<_, i64>(4)? as u64,
                weekdays: r.get::<_, i64>(5)? as u8,
                start_hour: r.get::<_, i64>(6)? as u8,
                end_hour: r.get::<_, i64>(7)? as u8,
                created_at: r.get::<_, i64>(8)? as u64,
            })
        })
        .ok()
        .map(|i| i.filter_map(|x| x.ok()).collect())
        .unwrap_or_default()
    }

    /// Upsert a silence (`id` generated by the caller).
    pub fn upsert_alerting_silence(&mut self, row: &SilenceRuleRow) {
        let _ = self.conn.execute(
            "INSERT INTO alerting_silences
                (id, name, kind_pattern, starts_at, ends_at, weekdays, start_hour, end_hour, created_at)
             VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9)
             ON CONFLICT(id) DO UPDATE SET
                name=excluded.name,
                kind_pattern=excluded.kind_pattern,
                starts_at=excluded.starts_at,
                ends_at=excluded.ends_at,
                weekdays=excluded.weekdays,
                start_hour=excluded.start_hour,
                end_hour=excluded.end_hour",
            rusqlite::params![
                row.id,
                row.name,
                row.kind_pattern,
                row.starts_at as i64,
                row.ends_at as i64,
                row.weekdays as i64,
                row.start_hour as i64,
                row.end_hour as i64,
                row.created_at as i64,
            ],
        );
    }

    /// Delete a silence. Returns whether it was actually deleted.
    pub fn delete_alerting_silence(&mut self, id: &str) -> bool {
        self.conn
            .execute(
                "DELETE FROM alerting_silences WHERE id = ?1",
                rusqlite::params![id],
            )
            .unwrap_or(0)
            > 0
    }

    /// List all ack records (may include expired ones — the UI filters display by ack_until itself).
    pub fn list_alerting_acks(&self) -> Vec<AckRuleRow> {
        let Ok(mut stmt) = self.conn.prepare(
            "SELECT id, kind_pattern, ack_until, created_at FROM alerting_acks ORDER BY ack_until DESC",
        ) else {
            return Vec::new();
        };
        stmt.query_map([], |r| {
            Ok(AckRuleRow {
                id: r.get(0)?,
                kind_pattern: r.get(1)?,
                ack_until: r.get::<_, i64>(2)? as u64,
                created_at: r.get::<_, i64>(3)? as u64,
            })
        })
        .ok()
        .map(|i| i.filter_map(|x| x.ok()).collect())
        .unwrap_or_default()
    }

    /// List ack records that have not expired (used by the dispatch check).
    pub fn list_active_acks(&self, now_ts: u64) -> Vec<AckRuleRow> {
        let Ok(mut stmt) = self.conn.prepare(
            "SELECT id, kind_pattern, ack_until, created_at FROM alerting_acks WHERE ack_until > ?1",
        ) else {
            return Vec::new();
        };
        stmt.query_map(rusqlite::params![now_ts as i64], |r| {
            Ok(AckRuleRow {
                id: r.get(0)?,
                kind_pattern: r.get(1)?,
                ack_until: r.get::<_, i64>(2)? as u64,
                created_at: r.get::<_, i64>(3)? as u64,
            })
        })
        .ok()
        .map(|i| i.filter_map(|x| x.ok()).collect())
        .unwrap_or_default()
    }

    /// Upsert an ack.
    pub fn upsert_alerting_ack(&mut self, row: &AckRuleRow) {
        let _ = self.conn.execute(
            "INSERT INTO alerting_acks (id, kind_pattern, ack_until, created_at)
             VALUES (?1, ?2, ?3, ?4)
             ON CONFLICT(id) DO UPDATE SET
                kind_pattern=excluded.kind_pattern,
                ack_until=excluded.ack_until",
            rusqlite::params![
                row.id,
                row.kind_pattern,
                row.ack_until as i64,
                row.created_at as i64,
            ],
        );
    }

    /// Delete an ack.
    pub fn delete_alerting_ack(&mut self, id: &str) -> bool {
        self.conn
            .execute(
                "DELETE FROM alerting_acks WHERE id = ?1",
                rusqlite::params![id],
            )
            .unwrap_or(0)
            > 0
    }

    /// Clear all expired acks (`ack_until <= now`).
    pub fn clear_expired_acks(&mut self, now_ts: u64) -> usize {
        self.conn
            .execute(
                "DELETE FROM alerting_acks WHERE ack_until <= ?1",
                rusqlite::params![now_ts as i64],
            )
            .unwrap_or(0)
    }

    /// All DSL route rules (by priority ASC, then created_at ASC). Added in Phase 51.
    pub fn list_alerting_routes(&self) -> Vec<RouteRuleRow> {
        let Ok(mut stmt) = self.conn.prepare(
            "SELECT id, name, priority, enabled, kind_pattern, target_endpoint_ids_json,
                    payload_path, payload_match, tags_json, recipients_json, seen_in_last_json, created_at
             FROM alerting_routes ORDER BY priority ASC, created_at ASC",
        ) else {
            return Vec::new();
        };
        stmt.query_map([], |r| {
            let ids_json: String = r.get(5)?;
            let tags_json: Option<String> = r.get(8)?;
            let recipients_json: Option<String> = r.get(9)?;
            let seen_in_last_json: Option<String> = r.get(10)?;
            let target_endpoint_ids: Vec<String> =
                serde_json::from_str(&ids_json).unwrap_or_default();
            let tags: Vec<String> = tags_json
                .as_deref()
                .and_then(|s| serde_json::from_str(s).ok())
                .unwrap_or_default();
            let recipients: Vec<String> = recipients_json
                .as_deref()
                .and_then(|s| serde_json::from_str(s).ok())
                .unwrap_or_default();
            Ok(RouteRuleRow {
                id: r.get(0)?,
                name: r.get(1)?,
                priority: r.get(2)?,
                enabled: r.get::<_, i64>(3)? != 0,
                kind_pattern: r.get(4)?,
                payload_path: r.get(6)?,
                payload_match: r.get(7)?,
                target_endpoint_ids,
                recipients,
                tags,
                seen_in_last_json,
                created_at: r.get(11)?,
            })
        })
        .ok()
        .map(|it| it.filter_map(|r| r.ok()).collect())
        .unwrap_or_default()
    }

    /// Upsert a route (id overwrites; created_at keeps the old value to avoid UI jumps). Added in Phase 51.
    pub fn upsert_alerting_route(&mut self, row: &RouteRuleRow) {
        let ids_json =
            serde_json::to_string(&row.target_endpoint_ids).unwrap_or_else(|_| "[]".into());
        let tags_json = serde_json::to_string(&row.tags).unwrap_or_else(|_| "[]".into());
        let recipients_json =
            serde_json::to_string(&row.recipients).unwrap_or_else(|_| "[]".into());
        let _ = self.conn.execute(
            "INSERT INTO alerting_routes
             (id, name, priority, enabled, kind_pattern, payload_path, payload_match,
              target_endpoint_ids_json, tags_json, recipients_json, seen_in_last_json, created_at)
             VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10, ?11, ?12)
             ON CONFLICT(id) DO UPDATE SET
                name=excluded.name,
                priority=excluded.priority,
                enabled=excluded.enabled,
                kind_pattern=excluded.kind_pattern,
                payload_path=excluded.payload_path,
                payload_match=excluded.payload_match,
                target_endpoint_ids_json=excluded.target_endpoint_ids_json,
                tags_json=excluded.tags_json,
                recipients_json=excluded.recipients_json,
                seen_in_last_json=excluded.seen_in_last_json",
            rusqlite::params![
                row.id,
                row.name,
                row.priority,
                row.enabled as i64,
                row.kind_pattern,
                row.payload_path,
                row.payload_match,
                ids_json,
                tags_json,
                recipients_json,
                row.seen_in_last_json,
                row.created_at as i64,
            ],
        );
    }

    /// Delete a route. Added in Phase 51.
    pub fn delete_alerting_route(&mut self, id: &str) -> bool {
        self.conn
            .execute(
                "DELETE FROM alerting_routes WHERE id = ?1",
                rusqlite::params![id],
            )
            .unwrap_or(0)
            > 0
    }

    /// Clear all routes (for atomic import). Added in Phase 51.
    pub fn clear_alerting_routes(&mut self) -> usize {
        self.conn
            .execute("DELETE FROM alerting_routes", [])
            .unwrap_or(0)
    }

    /// All recipients (by created_at ASC). Added in Phase 67.
    pub fn list_alerting_recipients(&self) -> Vec<RecipientRow> {
        let Ok(mut stmt) = self.conn.prepare(
            "SELECT id, name, kind, config_json, enabled, created_at
             FROM alerting_recipients ORDER BY created_at ASC",
        ) else {
            return Vec::new();
        };
        stmt.query_map([], |r| {
            let cfg: String = r.get(3)?;
            let config: serde_json::Value =
                serde_json::from_str(&cfg).unwrap_or_else(|_| serde_json::json!({}));
            Ok(RecipientRow {
                id: r.get(0)?,
                name: r.get(1)?,
                kind: r.get(2)?,
                config,
                enabled: r.get::<_, i64>(4)? != 0,
                created_at: r.get::<_, i64>(5)? as u64,
            })
        })
        .ok()
        .map(|it| it.filter_map(|x| x.ok()).collect())
        .unwrap_or_default()
    }

    /// Upsert recipient. A `name` UNIQUE conflict → returns Err (handled by the caller's upper layer).
    /// Added in Phase 67.
    pub fn upsert_alerting_recipient(&mut self, row: &RecipientRow) -> Result<(), String> {
        let config_json = serde_json::to_string(&row.config).unwrap_or_else(|_| "{}".into());
        self.conn
            .execute(
                "INSERT INTO alerting_recipients
                    (id, name, kind, config_json, enabled, created_at)
                 VALUES (?1, ?2, ?3, ?4, ?5, ?6)
                 ON CONFLICT(id) DO UPDATE SET
                    name=excluded.name,
                    kind=excluded.kind,
                    config_json=excluded.config_json,
                    enabled=excluded.enabled",
                rusqlite::params![
                    row.id,
                    row.name,
                    row.kind,
                    config_json,
                    if row.enabled { 1i64 } else { 0i64 },
                    row.created_at as i64,
                ],
            )
            .map_err(|e| {
                let msg = e.to_string();
                if msg.contains("UNIQUE") {
                    format!("recipient name '{}' already exists", row.name)
                } else {
                    format!("upsert recipient: {msg}")
                }
            })?;
        Ok(())
    }

    /// Delete a recipient + cascade-clean dangling refs to this id in routes.recipients.
    /// Returns (deleted, routes_cleared). Added in Phase 67.
    pub fn delete_alerting_recipient(&mut self, id: &str) -> (bool, usize) {
        let n = self
            .conn
            .execute(
                "DELETE FROM alerting_recipients WHERE id = ?1",
                rusqlite::params![id],
            )
            .unwrap_or(0);
        let mut cleared = 0usize;
        if n > 0 {
            // collect routes referencing this id (`webhook:{id}` or `recipient:{id}`)
            let rows = self.list_alerting_routes();
            for row in rows {
                let before = row.recipients.len();
                let mut new_row = row.clone();
                let filtered: Vec<String> = new_row
                    .recipients
                    .drain(..)
                    .filter(|c| {
                        !(c.starts_with(&format!("webhook:{id}"))
                            || c.starts_with(&format!("recipient:{id}")))
                    })
                    .collect();
                if filtered.len() < before {
                    new_row.recipients = filtered;
                    self.upsert_alerting_route(&new_row);
                    cleared += 1;
                }
            }
        }
        (n > 0, cleared)
    }

    /// All hints (by source ASC). Added in Phase 53.
    pub fn list_alerting_severity_hints(&self) -> Vec<SeverityHintRow> {
        let Ok(mut stmt) = self.conn.prepare(
            "SELECT source, severity, origin, plugin_id, updated_at
             FROM alerting_severity_hints ORDER BY source ASC",
        ) else {
            return Vec::new();
        };
        stmt.query_map([], |r| {
            Ok(SeverityHintRow {
                source: r.get(0)?,
                severity: r.get(1)?,
                origin: r.get(2)?,
                plugin_id: r.get(3)?,
                updated_at: r.get(4)?,
            })
        })
        .ok()
        .map(|it| it.filter_map(|r| r.ok()).collect())
        .unwrap_or_default()
    }

    /// Upsert a hint. Added in Phase 53.
    pub fn upsert_alerting_severity_hint(
        &mut self,
        source: &str,
        severity: &str,
        origin: &str,
        plugin_id: Option<&str>,
        updated_at: i64,
    ) -> Result<(), String> {
        let ok = self.conn.execute(
            "INSERT INTO alerting_severity_hints (source, severity, origin, plugin_id, updated_at)
             VALUES (?1, ?2, ?3, ?4, ?5)
             ON CONFLICT(source, origin) DO UPDATE SET severity=?2, plugin_id=?4, updated_at=?5",
            rusqlite::params![source, severity, origin, plugin_id, updated_at],
        );
        match ok {
            Ok(_) => Ok(()),
            Err(e) => Err(format!("upsert severity hint failed: {e}")),
        }
    }

    pub fn delete_alerting_severity_hint_by_source_and_origin(
        &mut self,
        source: &str,
        origin: &str,
    ) -> bool {
        self.conn
            .execute(
                "DELETE FROM alerting_severity_hints WHERE source = ?1 AND origin = ?2",
                rusqlite::params![source, origin],
            )
            .unwrap_or(0)
            > 0
    }

    /// Batch-delete hints matching (origin, plugin_id), returning the delete count. Added in Phase 53.
    pub fn delete_alerting_severity_hints_by_origin_plugin(
        &mut self,
        origin: &str,
        plugin_id: &str,
    ) -> usize {
        self.conn
            .execute(
                "DELETE FROM alerting_severity_hints WHERE origin = ?1 AND plugin_id = ?2",
                rusqlite::params![origin, plugin_id],
            )
            .unwrap_or(0)
    }

    /// Clear all hints with origin user. Added in Phase 53, returns the delete count.
    pub fn clear_user_alerting_severity_hints(&mut self) -> usize {
        self.conn
            .execute(
                "DELETE FROM alerting_severity_hints WHERE origin = 'user'",
                [],
            )
            .unwrap_or(0)
    }

    /// Look up the hint matching (source, origin) (single row). Added in Phase 53.
    pub fn get_alerting_severity_hint(
        &self,
        source: &str,
        origin: &str,
    ) -> Option<SeverityHintRow> {
        let mut stmt = self
            .conn
            .prepare(
                "SELECT source, severity, origin, plugin_id, updated_at
             FROM alerting_severity_hints WHERE source = ?1 AND origin = ?2 LIMIT 1",
            )
            .ok()?;
        stmt.query_row(rusqlite::params![source, origin], |r| {
            Ok(SeverityHintRow {
                source: r.get(0)?,
                severity: r.get(1)?,
                origin: r.get(2)?,
                plugin_id: r.get(3)?,
                updated_at: r.get(4)?,
            })
        })
        .ok()
    }

    /// Phase 39 — all hotkey bindings. combo is the case-normalized string (e.g. "Cmd+Shift+K").
    pub fn list_hotkeys(&self) -> Vec<HotkeyRow> {
        let Ok(mut stmt) = self
            .conn
            .prepare("SELECT combo, label, payload, created_at, updated_at FROM hotkey_binding ORDER BY combo")
        else {
            return Vec::new();
        };
        stmt.query_map([], |r| {
            Ok(HotkeyRow {
                combo: r.get(0)?,
                label: r.get(1)?,
                payload: r.get(2)?,
                created_at: r.get(3)?,
                updated_at: r.get(4)?,
            })
        })
        .ok()
        .map(|i| i.filter_map(|x| x.ok()).collect())
        .unwrap_or_default()
    }

    /// Record a capability call + latency. Used by the Phase 30 dashboard.
    /// Phase 31: adds result + error_kind, failure classification.
    pub fn record_capability_call(
        &mut self,
        cap: &str,
        plugin: &str,
        elapsed_ms: i64,
        ts: u64,
        result: &str,
        error_kind: Option<&str>,
    ) {
        let _ = self.conn.execute(
            "INSERT INTO capability_stats (capability, plugin_id, elapsed_ms, ts, result, error_kind)
             VALUES (?1, ?2, ?3, ?4, ?5, ?6)",
            rusqlite::params![cap, plugin, elapsed_ms, ts as i64, result, error_kind],
        );
    }

    /// Aggregate the latest N calls per (capability, plugin_id) pair: count + avg + p50 + p95 + last_used + fail_count + errors.
    /// Computes percentiles in memory (N≤500 to prevent blowup), not via SQLite math functions. p50/p95 use only result='ok' samples; failed times are excluded from the latency distribution.
    pub fn capability_stats_summary(&self, samples_per_pair: usize) -> Vec<CapabilityStat> {
        let n = samples_per_pair.max(10).min(500);
        // take the latest n per pair: use a subquery to find the n newest ts for each (cap, plugin), then aggregate.
        // SQLite has no LATERAL, so use the window function ROW_NUMBER() OVER (PARTITION BY ... ORDER BY ts DESC).
        let Ok(mut stmt) = self.conn.prepare(
            "SELECT capability, plugin_id, elapsed_ms, ts, result, error_kind FROM (
                SELECT capability, plugin_id, elapsed_ms, ts, result, error_kind,
                       ROW_NUMBER() OVER (PARTITION BY capability, plugin_id ORDER BY ts DESC) AS rn
                FROM capability_stats
             ) WHERE rn <= ?1 ORDER BY capability ASC, ts DESC",
        ) else {
            return Vec::new();
        };
        // (cap, plugin, elapsed, ts, result, error_kind)
        let rows: Vec<(String, String, i64, i64, String, Option<String>)> = stmt
            .query_map([n as i64], |r| {
                Ok((
                    r.get(0)?,
                    r.get(1)?,
                    r.get(2)?,
                    r.get(3)?,
                    r.get(4)?,
                    r.get(5)?,
                ))
            })
            .ok()
            .map(|i| i.filter_map(|x| x.ok()).collect())
            .unwrap_or_default();
        // group by (cap, plugin)
        use std::collections::BTreeMap;
        let mut groups: BTreeMap<(String, String), Vec<(i64, i64, String, Option<String>)>> =
            BTreeMap::new();
        let mut last_used: std::collections::HashMap<(String, String), u64> = Default::default();
        for (cap, plugin, elapsed, ts, result, error_kind) in rows {
            groups
                .entry((cap.clone(), plugin.clone()))
                .or_default()
                .push((elapsed, ts, result, error_kind));
            let key = (cap, plugin);
            let entry = last_used.entry(key).or_insert(0);
            if (ts as u64) > *entry {
                *entry = ts as u64;
            }
        }
        let mut out: Vec<CapabilityStat> = groups
            .into_iter()
            .map(|((capability, plugin_id), mut samples)| {
                let last_used_at = last_used
                    .remove(&(capability.clone(), plugin_id.clone()))
                    .unwrap_or(0);
                let count = samples.len() as i64;
                // compute latency percentiles from ok only (a failed timeout=60000 would pollute p95)
                let mut ok_elapsed: Vec<i64> = samples
                    .iter()
                    .filter(|s| s.2 == "ok")
                    .map(|s| s.0)
                    .collect();
                ok_elapsed.sort_unstable();
                let (avg_ms, p50_ms, p95_ms) = if ok_elapsed.is_empty() {
                    (0.0, 0, 0)
                } else {
                    let sum: i64 = ok_elapsed.iter().sum();
                    let avg = sum as f64 / ok_elapsed.len() as f64;
                    let p50 = ok_elapsed[ok_elapsed.len() / 2];
                    let p95_idx = ((ok_elapsed.len() as f64 * 0.95).ceil() as usize)
                        .saturating_sub(1)
                        .min(ok_elapsed.len() - 1);
                    let p95 = ok_elapsed[p95_idx];
                    ((avg * 100.0).round() / 100.0, p50, p95)
                };
                // failure bucketing
                let mut errors: BTreeMap<String, i64> = BTreeMap::new();
                let mut fail_count: i64 = 0;
                for (_, _, result, error_kind) in &samples {
                    if result != "ok" {
                        fail_count += 1;
                        let kind = error_kind.clone().unwrap_or_else(|| "unknown".to_string());
                        *errors.entry(kind).or_insert(0) += 1;
                    }
                }
                CapabilityStat {
                    capability,
                    plugin_id,
                    count,
                    avg_ms,
                    p50_ms,
                    p95_ms,
                    last_used_at,
                    fail_count,
                    errors,
                }
            })
            .collect();
        // show to the UI by count descending (hot paths first)
        out.sort_by(|a, b| b.count.cmp(&a.count).then(a.capability.cmp(&b.capability)));
        out
    }

    fn aggregation_row_from_stmt(r: &rusqlite::Row) -> rusqlite::Result<AggregationRuleRow> {
        Ok(AggregationRuleRow {
            id: r.get(0)?,
            name: r.get(1)?,
            kind_pattern: r.get(2)?,
            window_secs: r.get::<_, i64>(3)? as u64,
            threshold_count: r.get::<_, i64>(4)? as u32,
            action: r.get(5)?,
            target_severity: r.get(6)?,
            enabled: r.get::<_, i64>(7)? != 0,
            created_at: r.get::<_, i64>(8)? as u64,
        })
    }

    /// All frequency-threshold rules (added in Phase 54). Phase 51 routes sort by priority similarly; here it is by created_at ASC.
    pub fn list_alerting_aggregations(&self) -> Vec<AggregationRuleRow> {
        let Ok(mut stmt) = self.conn.prepare(
            "SELECT id, name, kind_pattern, window_secs, threshold_count, action,
                    target_severity, enabled, created_at
             FROM alerting_aggregations ORDER BY created_at ASC",
        ) else {
            return Vec::new();
        };
        stmt.query_map([], Self::aggregation_row_from_stmt)
            .ok()
            .map(|it| it.filter_map(|r| r.ok()).collect())
            .unwrap_or_default()
    }

    /// Enabled rules only (added in Phase 54).
    pub fn list_enabled_alerting_aggregations(&self) -> Vec<AggregationRuleRow> {
        let Ok(mut stmt) = self.conn.prepare(
            "SELECT id, name, kind_pattern, window_secs, threshold_count, action,
                    target_severity, enabled, created_at
             FROM alerting_aggregations WHERE enabled = 1 ORDER BY created_at ASC",
        ) else {
            return Vec::new();
        };
        stmt.query_map([], Self::aggregation_row_from_stmt)
            .ok()
            .map(|it| it.filter_map(|r| r.ok()).collect())
            .unwrap_or_default()
    }

    /// Upsert an aggregation rule (added in Phase 54). id overwrites; created_at keeps the old value (to avoid UI time jumps).
    pub fn upsert_alerting_aggregation(&mut self, row: &AggregationRuleRow) {
        let _ = self.conn.execute(
            "INSERT INTO alerting_aggregations
             (id, name, kind_pattern, window_secs, threshold_count, action,
              target_severity, enabled, created_at)
             VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9)
             ON CONFLICT(id) DO UPDATE SET name=?2, kind_pattern=?3, window_secs=?4,
                threshold_count=?5, action=?6, target_severity=?7, enabled=?8",
            rusqlite::params![
                row.id,
                row.name,
                row.kind_pattern,
                row.window_secs as i64,
                row.threshold_count as i64,
                row.action,
                row.target_severity,
                row.enabled as i64,
                row.created_at as i64,
            ],
        );
    }

    pub fn delete_alerting_aggregation(&mut self, id: &str) -> bool {
        self.conn
            .execute(
                "DELETE FROM alerting_aggregations WHERE id = ?1",
                rusqlite::params![id],
            )
            .unwrap_or(0)
            > 0
    }

    pub fn clear_alerting_aggregations(&mut self) -> usize {
        self.conn
            .execute("DELETE FROM alerting_aggregations", [])
            .unwrap_or(0)
    }

    fn correlation_row_from_stmt(r: &rusqlite::Row) -> rusqlite::Result<CorrelationRuleRow> {
        Ok(CorrelationRuleRow {
            id: r.get(0)?,
            name: r.get(1)?,
            kind_pattern_a: r.get(2)?,
            kind_pattern_b: r.get(3)?,
            window_secs: r.get::<_, i64>(4)? as u64,
            enabled: r.get::<_, i64>(5)? != 0,
            created_at: r.get::<_, i64>(6)? as u64,
        })
    }

    pub fn list_alerting_correlations(&self) -> Vec<CorrelationRuleRow> {
        let Ok(mut stmt) = self.conn.prepare(
            "SELECT id, name, kind_pattern_a, kind_pattern_b, window_secs,
                    enabled, created_at
             FROM alerting_correlations ORDER BY created_at ASC",
        ) else {
            return Vec::new();
        };
        stmt.query_map([], Self::correlation_row_from_stmt)
            .ok()
            .map(|it| it.filter_map(|r| r.ok()).collect())
            .unwrap_or_default()
    }

    pub fn list_enabled_alerting_correlations(&self) -> Vec<CorrelationRuleRow> {
        let Ok(mut stmt) = self.conn.prepare(
            "SELECT id, name, kind_pattern_a, kind_pattern_b, window_secs,
                    enabled, created_at
             FROM alerting_correlations WHERE enabled = 1 ORDER BY created_at ASC",
        ) else {
            return Vec::new();
        };
        stmt.query_map([], Self::correlation_row_from_stmt)
            .ok()
            .map(|it| it.filter_map(|r| r.ok()).collect())
            .unwrap_or_default()
    }

    pub fn upsert_alerting_correlation(&mut self, row: &CorrelationRuleRow) {
        let _ = self.conn.execute(
            "INSERT INTO alerting_correlations
             (id, name, kind_pattern_a, kind_pattern_b, window_secs, enabled, created_at)
             VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7)
             ON CONFLICT(id) DO UPDATE SET name=?2, kind_pattern_a=?3, kind_pattern_b=?4,
                window_secs=?5, enabled=?6",
            rusqlite::params![
                row.id,
                row.name,
                row.kind_pattern_a,
                row.kind_pattern_b,
                row.window_secs as i64,
                row.enabled as i64,
                row.created_at as i64,
            ],
        );
    }

    pub fn delete_alerting_correlation(&mut self, id: &str) -> bool {
        self.conn
            .execute(
                "DELETE FROM alerting_correlations WHERE id = ?1",
                rusqlite::params![id],
            )
            .unwrap_or(0)
            > 0
    }

    pub fn clear_alerting_correlations(&mut self) -> usize {
        self.conn
            .execute("DELETE FROM alerting_correlations", [])
            .unwrap_or(0)
    }

    fn escalation_row_from_stmt(r: &rusqlite::Row) -> rusqlite::Result<EscalationRuleRow> {
        let ids_json: String = r.get(5)?;
        let target_endpoint_ids: Option<Vec<String>> = if ids_json.is_empty() || ids_json == "[]" {
            None
        } else {
            serde_json::from_str(&ids_json).ok()
        };
        Ok(EscalationRuleRow {
            id: r.get(0)?,
            name: r.get(1)?,
            kind_pattern: r.get(2)?,
            escalate_after_secs: r.get::<_, i64>(3)? as u64,
            target_severity: r.get(4)?,
            target_endpoint_ids,
            enabled: r.get::<_, i64>(6)? != 0,
            created_at: r.get::<_, i64>(7)? as u64,
        })
    }

    pub fn list_alerting_escalations(&self) -> Vec<EscalationRuleRow> {
        let Ok(mut stmt) = self.conn.prepare(
            "SELECT id, name, kind_pattern, escalate_after_secs, target_severity,
                    target_endpoint_ids, enabled, created_at
             FROM alerting_escalations ORDER BY created_at ASC",
        ) else {
            return Vec::new();
        };
        stmt.query_map([], Self::escalation_row_from_stmt)
            .ok()
            .map(|it| it.filter_map(|r| r.ok()).collect())
            .unwrap_or_default()
    }

    pub fn list_enabled_alerting_escalations(&self) -> Vec<EscalationRuleRow> {
        let Ok(mut stmt) = self.conn.prepare(
            "SELECT id, name, kind_pattern, escalate_after_secs, target_severity,
                    target_endpoint_ids, enabled, created_at
             FROM alerting_escalations WHERE enabled = 1 ORDER BY created_at ASC",
        ) else {
            return Vec::new();
        };
        stmt.query_map([], Self::escalation_row_from_stmt)
            .ok()
            .map(|it| it.filter_map(|r| r.ok()).collect())
            .unwrap_or_default()
    }

    pub fn upsert_alerting_escalation(&mut self, row: &EscalationRuleRow) {
        let ids_json =
            serde_json::to_string(row.target_endpoint_ids.as_ref().unwrap_or(&Vec::new()))
                .unwrap_or_else(|_| "[]".into());
        let _ = self.conn.execute(
            "INSERT INTO alerting_escalations
             (id, name, kind_pattern, escalate_after_secs, target_severity,
              target_endpoint_ids, enabled, created_at)
             VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8)
             ON CONFLICT(id) DO UPDATE SET name=?2, kind_pattern=?3, escalate_after_secs=?4,
                target_severity=?5, target_endpoint_ids=?6, enabled=?7",
            rusqlite::params![
                row.id,
                row.name,
                row.kind_pattern,
                row.escalate_after_secs as i64,
                row.target_severity,
                ids_json,
                row.enabled as i64,
                row.created_at as i64,
            ],
        );
    }

    pub fn delete_alerting_escalation(&mut self, id: &str) -> bool {
        self.conn
            .execute(
                "DELETE FROM alerting_escalations WHERE id = ?1",
                rusqlite::params![id],
            )
            .unwrap_or(0)
            > 0
    }

    pub fn clear_alerting_escalations(&mut self) -> usize {
        self.conn
            .execute("DELETE FROM alerting_escalations", [])
            .unwrap_or(0)
    }
}
