//! alerting failed deliveries (the dead-letter queue).
//! Mechanical move from core/storage/alerting_tables.rs.

use super::*;

impl Storage {
    /// Write a dead-letter record (state='pending'). `id` is generated by the caller (nano timestamp or uuid).
    /// Phase 49 adds `endpoint_id`: None means it came from the Phase 47 single-endpoint compatibility path.
    pub fn insert_failed_delivery(
        &mut self,
        id: &str,
        source: &str,
        url: &str,
        payload_json: &str,
        now_ts: u64,
        max_attempts: u32,
        next_retry_ts: u64,
        last_error: &str,
        endpoint_id: Option<&str>,
    ) {
        let _ = self.conn.execute(
            "INSERT INTO alerting_failed_deliveries
                (id, source, url, payload, first_attempt_ts, last_attempt_ts,
                 attempts, max_attempts, last_error, next_retry_ts, state, endpoint_id)
             VALUES (?1, ?2, ?3, ?4, ?5, ?5, 1, ?6, ?7, ?8, 'pending', ?9)",
            rusqlite::params![
                id,
                source,
                url,
                payload_json,
                now_ts as i64,
                max_attempts as i64,
                last_error,
                next_retry_ts as i64,
                endpoint_id,
            ],
        );
    }

    /// List dead letters for a given state (state nullable: "pending"/"exhausted"/"resolved"). By next_retry_ts ascending.
    pub fn list_failed_deliveries(
        &self,
        state: Option<&str>,
        limit: usize,
    ) -> Vec<FailedDeliveryRow> {
        let limit = limit.max(1).min(2000);
        let (sql, use_state): (&str, bool) = match state {
            Some(s) if !s.is_empty() => (
                "SELECT id, source, url, payload, first_attempt_ts, last_attempt_ts,
                        attempts, max_attempts, last_error, next_retry_ts, state, endpoint_id
                   FROM alerting_failed_deliveries
                   WHERE state = ?1
                   ORDER BY next_retry_ts ASC, last_attempt_ts DESC
                   LIMIT ?2",
                true,
            ),
            _ => (
                "SELECT id, source, url, payload, first_attempt_ts, last_attempt_ts,
                        attempts, max_attempts, last_error, next_retry_ts, state, endpoint_id
                   FROM alerting_failed_deliveries
                   ORDER BY next_retry_ts ASC, last_attempt_ts DESC
                   LIMIT ?1",
                false,
            ),
        };
        let Ok(mut stmt) = self.conn.prepare(sql) else {
            return Vec::new();
        };
        let mapper = |r: &rusqlite::Row| -> rusqlite::Result<FailedDeliveryRow> {
            let payload: String = r.get(3)?;
            Ok(FailedDeliveryRow {
                id: r.get(0)?,
                source: r.get(1)?,
                url: r.get(2)?,
                payload,
                first_attempt_ts: r.get::<_, i64>(4)? as u64,
                last_attempt_ts: r.get::<_, i64>(5)? as u64,
                attempts: r.get::<_, i64>(6)? as u32,
                max_attempts: r.get::<_, i64>(7)? as u32,
                last_error: r.get(8)?,
                next_retry_ts: r.get::<_, i64>(9)? as u64,
                state: r.get(10)?,
                endpoint_id: r.get(11)?,
            })
        };
        if use_state {
            stmt.query_map(rusqlite::params![state.unwrap(), limit as i64], mapper)
                .ok()
                .map(|i| i.filter_map(|x| x.ok()).collect())
                .unwrap_or_default()
        } else {
            stmt.query_map(rusqlite::params![limit as i64], mapper)
                .ok()
                .map(|i| i.filter_map(|x| x.ok()).collect())
                .unwrap_or_default()
        }
    }

    /// Fetch due pending rows (called by the retry loop). limit defaults to 50 to avoid scanning too many at once.
    pub fn fetch_due_failed_deliveries(&self, now_ts: u64, limit: usize) -> Vec<FailedDeliveryRow> {
        let Ok(mut stmt) = self.conn.prepare(
            "SELECT id, source, url, payload, first_attempt_ts, last_attempt_ts,
                    attempts, max_attempts, last_error, next_retry_ts, state, endpoint_id
               FROM alerting_failed_deliveries
               WHERE state = 'pending' AND next_retry_ts <= ?1
               ORDER BY next_retry_ts ASC
               LIMIT ?2",
        ) else {
            return Vec::new();
        };
        stmt.query_map(rusqlite::params![now_ts as i64, limit as i64], |r| {
            let payload: String = r.get(3)?;
            Ok(FailedDeliveryRow {
                id: r.get(0)?,
                source: r.get(1)?,
                url: r.get(2)?,
                payload,
                first_attempt_ts: r.get::<_, i64>(4)? as u64,
                last_attempt_ts: r.get::<_, i64>(5)? as u64,
                attempts: r.get::<_, i64>(6)? as u32,
                max_attempts: r.get::<_, i64>(7)? as u32,
                last_error: r.get(8)?,
                next_retry_ts: r.get::<_, i64>(9)? as u64,
                state: r.get(10)?,
                endpoint_id: r.get(11)?,
            })
        })
        .ok()
        .map(|i| i.filter_map(|x| x.ok()).collect())
        .unwrap_or_default()
    }

    /// Phase 49: delete all dead letters for the given endpoint (cascade cleanup).
    pub fn delete_failed_deliveries_for_endpoint(&mut self, endpoint_id: &str) -> usize {
        self.conn
            .execute(
                "DELETE FROM alerting_failed_deliveries WHERE endpoint_id = ?1",
                rusqlite::params![endpoint_id],
            )
            .unwrap_or(0)
    }

    /// Update a failed retry: attempts++, refreshing last_attempt_ts / last_error / next_retry_ts.
    /// Passing next_retry_ts = 0 means "exhausted"; state switches to 'exhausted'.
    pub fn update_failed_delivery_retry(
        &mut self,
        id: &str,
        now_ts: u64,
        next_retry_ts: u64,
        last_error: &str,
    ) {
        let _ = self.conn.execute(
            "UPDATE alerting_failed_deliveries
                SET attempts = attempts + 1,
                    last_attempt_ts = ?2,
                    last_error = ?3,
                    next_retry_ts = ?4,
                    state = CASE WHEN ?4 = 0 THEN 'exhausted' ELSE 'pending' END
              WHERE id = ?1",
            rusqlite::params![id, now_ts as i64, last_error, next_retry_ts as i64],
        );
    }

    /// Mark as resolved (2xx response). state='resolved', kept for N days before cleanup.
    pub fn mark_failed_delivery_resolved(&mut self, id: &str, now_ts: u64) {
        let _ = self.conn.execute(
            "UPDATE alerting_failed_deliveries
                SET state = 'resolved', last_attempt_ts = ?2
              WHERE id = ?1",
            rusqlite::params![id, now_ts as i64],
        );
    }

    /// Manual retry: reset attempts to zero, state back to 'pending', next_retry_ts=now.
    pub fn reset_failed_delivery_for_retry(&mut self, id: &str, now_ts: u64) {
        let _ = self.conn.execute(
            "UPDATE alerting_failed_deliveries
                SET state = 'pending', attempts = 0, next_retry_ts = ?2, last_error = 'manual retry'
              WHERE id = ?1",
            rusqlite::params![id, now_ts as i64],
        );
    }

    /// Delete a dead letter.
    pub fn delete_failed_delivery(&mut self, id: &str) -> bool {
        let n = self
            .conn
            .execute(
                "DELETE FROM alerting_failed_deliveries WHERE id = ?1",
                rusqlite::params![id],
            )
            .unwrap_or(0);
        n > 0
    }

    /// Clear all exhausted + resolved rows (user manually empties the panel).
    pub fn clear_resolved_failed_deliveries(&mut self) -> usize {
        self.conn
            .execute(
                "DELETE FROM alerting_failed_deliveries WHERE state IN ('exhausted','resolved')",
                [],
            )
            .unwrap_or(0)
    }

    /// Prune resolved / exhausted rows older than retention_days (to avoid long-term buildup).
    pub fn prune_old_failed_deliveries(&mut self, now_ts: u64, retention_days: u32) {
        let cutoff = now_ts.saturating_sub((retention_days as u64).saturating_mul(86400));
        let _ = self.conn.execute(
            "DELETE FROM alerting_failed_deliveries
              WHERE state IN ('exhausted','resolved') AND last_attempt_ts < ?1",
            rusqlite::params![cutoff as i64],
        );
    }
}
