//! alerting endpoints (multi-endpoint fanout).
//! Mechanical move from core/storage/alerting_tables.rs.

use super::*;

impl Storage {
    /// Build one endpoint row from a SELECT of the 12 columns the endpoint queries share (same order).
    fn parse_endpoint_row(r: &rusqlite::Row) -> rusqlite::Result<AlertingEndpointRow> {
        let id: String = r.get(0)?;
        let name: String = r.get(1)?;
        let url: String = r.get(2)?;
        let enabled: i64 = r.get(3)?;
        let headers_json: String = r.get(4)?;
        let secret: String = r.get(5)?;
        let source_filter_json: String = r.get(6)?;
        let created_at: i64 = r.get(7)?;
        let schema_version: i64 = r.get(8)?;
        let template: Option<String> = r.get(9)?;
        let template_sample: Option<String> = r.get(10)?;
        let severity_overrides: Option<String> = r.get(11)?;
        let headers: Vec<(String, String)> =
            serde_json::from_str(&headers_json).unwrap_or_default();
        let source_filter: Vec<String> =
            serde_json::from_str(&source_filter_json).unwrap_or_default();
        Ok(AlertingEndpointRow {
            id,
            name,
            url,
            enabled: enabled != 0,
            headers,
            secret,
            source_filter,
            created_at: created_at as u64,
            schema_version: schema_version.max(0) as u32,
            template,
            template_sample,
            severity_overrides,
        })
    }

    /// List all endpoints, by created_at ascending.
    pub fn list_alerting_endpoints(&self) -> Vec<AlertingEndpointRow> {
        let Ok(mut stmt) = self.conn.prepare(
            "SELECT id, name, url, enabled, headers_json, secret, source_filter_json, created_at, schema_version, template, template_sample, severity_overrides_json
               FROM alerting_endpoints ORDER BY created_at ASC",
        ) else {
            return Vec::new();
        };
        stmt.query_map([], Self::parse_endpoint_row)
            .ok()
            .map(|i| i.filter_map(|x| x.ok()).collect())
            .unwrap_or_default()
    }

    /// List all enabled endpoints — used during dispatcher fanout.
    pub fn list_enabled_alerting_endpoints(&self) -> Vec<AlertingEndpointRow> {
        let Ok(mut stmt) = self.conn.prepare(
            "SELECT id, name, url, enabled, headers_json, secret, source_filter_json, created_at, schema_version, template, template_sample, severity_overrides_json
               FROM alerting_endpoints WHERE enabled = 1 ORDER BY created_at ASC",
        ) else {
            return Vec::new();
        };
        stmt.query_map([], Self::parse_endpoint_row)
            .ok()
            .map(|i| i.filter_map(|x| x.ok()).collect())
            .unwrap_or_default()
    }

    /// Get a single endpoint by id.
    pub fn get_alerting_endpoint(&self, id: &str) -> Option<AlertingEndpointRow> {
        let mut stmt = self
            .conn
            .prepare(
                "SELECT id, name, url, enabled, headers_json, secret, source_filter_json, created_at, schema_version, template, template_sample, severity_overrides_json
                   FROM alerting_endpoints WHERE id = ?1",
            )
            .ok()?;
        stmt.query_row(rusqlite::params![id], Self::parse_endpoint_row)
            .ok()
    }

    /// Upsert: update when there is an id, otherwise use the passed-in id (generated by the caller).
    pub fn upsert_alerting_endpoint(&mut self, row: &AlertingEndpointRow) {
        let headers_json = serde_json::to_string(&row.headers).unwrap_or_else(|_| "[]".into());
        let source_filter_json =
            serde_json::to_string(&row.source_filter).unwrap_or_else(|_| "[]".into());
        let _ = self.conn.execute(
            "INSERT INTO alerting_endpoints
                (id, name, url, enabled, headers_json, secret, source_filter_json, created_at, schema_version, template, template_sample, severity_overrides_json)
             VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10, ?11, ?12)
             ON CONFLICT(id) DO UPDATE SET
                name=excluded.name,
                url=excluded.url,
                enabled=excluded.enabled,
                headers_json=excluded.headers_json,
                secret=excluded.secret,
                source_filter_json=excluded.source_filter_json,
                schema_version=excluded.schema_version,
                template=excluded.template,
                template_sample=excluded.template_sample,
                severity_overrides_json=excluded.severity_overrides_json",
            rusqlite::params![
                row.id,
                row.name,
                row.url,
                if row.enabled { 1i64 } else { 0i64 },
                headers_json,
                row.secret,
                source_filter_json,
                row.created_at as i64,
                row.schema_version as i64,
                row.template.as_deref(),
                row.template_sample.as_deref(),
                row.severity_overrides.as_deref(),
            ],
        );
    }

    /// Delete an endpoint, cascading cleanup of its dead letters. Returns (endpoint_deleted, deliveries_deleted).
    pub fn delete_alerting_endpoint(&mut self, id: &str) -> (bool, usize) {
        let n = self
            .conn
            .execute(
                "DELETE FROM alerting_endpoints WHERE id = ?1",
                rusqlite::params![id],
            )
            .unwrap_or(0);
        let cleared = self.delete_failed_deliveries_for_endpoint(id);
        (n > 0, cleared)
    }
}
