//! alerting silences and acks.
//! Mechanical move from core/storage/alerting_tables.rs.

use super::*;

impl Storage {
    /// List all silence rules, by starts_at ascending.
    pub fn list_alerting_silences(&self) -> Vec<SilenceRuleRow> {
        let Ok(mut stmt) = self.conn.prepare(
            "SELECT id, name, kind_pattern, starts_at, ends_at, weekdays, start_hour, end_hour, created_at
               FROM alerting_silences ORDER BY starts_at ASC",
        ) else {
            return Vec::new();
        };
        stmt.query_map([], |r| {
            Ok(SilenceRuleRow {
                id: r.get(0)?,
                name: r.get(1)?,
                kind_pattern: r.get(2)?,
                starts_at: r.get::<_, i64>(3)? as u64,
                ends_at: r.get::<_, i64>(4)? as u64,
                weekdays: r.get::<_, i64>(5)? as u8,
                start_hour: r.get::<_, i64>(6)? as u8,
                end_hour: r.get::<_, i64>(7)? as u8,
                created_at: r.get::<_, i64>(8)? as u64,
            })
        })
        .ok()
        .map(|i| i.filter_map(|x| x.ok()).collect())
        .unwrap_or_default()
    }

    /// List all silences that could be active (ends_at > now + some buffer); the dispatch phase avoids querying all to prevent staleness.
    pub fn list_active_silences(&self, now_ts: u64) -> Vec<SilenceRuleRow> {
        let Ok(mut stmt) = self.conn.prepare(
            "SELECT id, name, kind_pattern, starts_at, ends_at, weekdays, start_hour, end_hour, created_at
               FROM alerting_silences WHERE ends_at > ?1 ORDER BY starts_at ASC",
        ) else {
            return Vec::new();
        };
        stmt.query_map(rusqlite::params![now_ts as i64], |r| {
            Ok(SilenceRuleRow {
                id: r.get(0)?,
                name: r.get(1)?,
                kind_pattern: r.get(2)?,
                starts_at: r.get::<_, i64>(3)? as u64,
                ends_at: r.get::<_, i64>(4)? as u64,
                weekdays: r.get::<_, i64>(5)? as u8,
                start_hour: r.get::<_, i64>(6)? as u8,
                end_hour: r.get::<_, i64>(7)? as u8,
                created_at: r.get::<_, i64>(8)? as u64,
            })
        })
        .ok()
        .map(|i| i.filter_map(|x| x.ok()).collect())
        .unwrap_or_default()
    }

    /// Upsert a silence (`id` generated by the caller).
    pub fn upsert_alerting_silence(&mut self, row: &SilenceRuleRow) {
        let _ = self.conn.execute(
            "INSERT INTO alerting_silences
                (id, name, kind_pattern, starts_at, ends_at, weekdays, start_hour, end_hour, created_at)
             VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9)
             ON CONFLICT(id) DO UPDATE SET
                name=excluded.name,
                kind_pattern=excluded.kind_pattern,
                starts_at=excluded.starts_at,
                ends_at=excluded.ends_at,
                weekdays=excluded.weekdays,
                start_hour=excluded.start_hour,
                end_hour=excluded.end_hour",
            rusqlite::params![
                row.id,
                row.name,
                row.kind_pattern,
                row.starts_at as i64,
                row.ends_at as i64,
                row.weekdays as i64,
                row.start_hour as i64,
                row.end_hour as i64,
                row.created_at as i64,
            ],
        );
    }

    /// Delete a silence. Returns whether it was actually deleted.
    pub fn delete_alerting_silence(&mut self, id: &str) -> bool {
        self.conn
            .execute(
                "DELETE FROM alerting_silences WHERE id = ?1",
                rusqlite::params![id],
            )
            .unwrap_or(0)
            > 0
    }

    /// List all ack records (may include expired ones — the UI filters display by ack_until itself).
    pub fn list_alerting_acks(&self) -> Vec<AckRuleRow> {
        let Ok(mut stmt) = self.conn.prepare(
            "SELECT id, kind_pattern, ack_until, created_at FROM alerting_acks ORDER BY ack_until DESC",
        ) else {
            return Vec::new();
        };
        stmt.query_map([], |r| {
            Ok(AckRuleRow {
                id: r.get(0)?,
                kind_pattern: r.get(1)?,
                ack_until: r.get::<_, i64>(2)? as u64,
                created_at: r.get::<_, i64>(3)? as u64,
            })
        })
        .ok()
        .map(|i| i.filter_map(|x| x.ok()).collect())
        .unwrap_or_default()
    }

    /// List ack records that have not expired (used by the dispatch check).
    pub fn list_active_acks(&self, now_ts: u64) -> Vec<AckRuleRow> {
        let Ok(mut stmt) = self.conn.prepare(
            "SELECT id, kind_pattern, ack_until, created_at FROM alerting_acks WHERE ack_until > ?1",
        ) else {
            return Vec::new();
        };
        stmt.query_map(rusqlite::params![now_ts as i64], |r| {
            Ok(AckRuleRow {
                id: r.get(0)?,
                kind_pattern: r.get(1)?,
                ack_until: r.get::<_, i64>(2)? as u64,
                created_at: r.get::<_, i64>(3)? as u64,
            })
        })
        .ok()
        .map(|i| i.filter_map(|x| x.ok()).collect())
        .unwrap_or_default()
    }

    /// Upsert an ack.
    pub fn upsert_alerting_ack(&mut self, row: &AckRuleRow) {
        let _ = self.conn.execute(
            "INSERT INTO alerting_acks (id, kind_pattern, ack_until, created_at)
             VALUES (?1, ?2, ?3, ?4)
             ON CONFLICT(id) DO UPDATE SET
                kind_pattern=excluded.kind_pattern,
                ack_until=excluded.ack_until",
            rusqlite::params![
                row.id,
                row.kind_pattern,
                row.ack_until as i64,
                row.created_at as i64,
            ],
        );
    }

    /// Delete an ack.
    pub fn delete_alerting_ack(&mut self, id: &str) -> bool {
        self.conn
            .execute(
                "DELETE FROM alerting_acks WHERE id = ?1",
                rusqlite::params![id],
            )
            .unwrap_or(0)
            > 0
    }

    /// Clear all expired acks (`ack_until <= now`).
    pub fn clear_expired_acks(&mut self, now_ts: u64) -> usize {
        self.conn
            .execute(
                "DELETE FROM alerting_acks WHERE ack_until <= ?1",
                rusqlite::params![now_ts as i64],
            )
            .unwrap_or(0)
    }
}
